import "./globals.css";
import Header from "@/components/common/Header";
import Providers from "@/redux/provider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="flex flex-col max-w-screen-2xl w-full mx-auto px-[0.625rem]">
                <Header />
                <Providers>{children}</Providers>
                {/* <main >{children}</main> */}
                {/* <Footer /> */}
            </body>
        </html>
    );
}
